name: tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                go: [1.8, 1.9, "1.10", 1.11, 1.12, 1.13, 1.14, 1.15, 1.16]

        steps:
            - name: setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}

            - uses: actions/checkout@v3
            - name: resolve dependencies
              run: go get -v -t -d ./...
            - name: build
              run: go build -v .
            - name: test
              run: go test -v .
